### ISSUE TITLE
[ Todos ] Member's

### ISSUE THREAD

**Issue by GangOn0215** [GangOn0215/base-couple-emotion-diary#2]
# todo
## 용어 정리
FE : Front
BE : Backend

#### 2022/10/26
- [x] first todo!
- [ ] FE validation 끝내기
  - [x] `memberState`를 이용하여 ` id, pw, pw2, name, email, phone number `  데이터를 순회한뒤 require부분들 체크한 후 `errorState` 에 `setErrorState` 를 이용하여 넣어주기 
  - [ ] `errorState`를 만든뒤 validation 통과 못했을때 FE 부분에서 error 문구 보이게 만들기 
- [ ] BE validation 끝내기

**Comment by GangOn0215** [comment]
로그인, 회원가입 완료
